### ISSUE TITLE
Production .env setup in Jenkins

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-design-applications#104]
Currently, there are a few environment variables set in .env in the Dockerfile like this:

    RUN echo "NODE_ENV=production" >> .env
    RUN echo "GA_ID=UA-63638898-8" >> .env
    RUN echo "HEAP_ID=2590460155" >> .env

This is not cached in docker though, so it slows down development.  Instead, Jenkins should copy these values to .env.

**Comment by justinmc** [comment]
@dionjwa Does https://github.com/Autodesk/molecular-design-applications/pull/118 resolve this issue?

**Comment by PeterRJones** [comment]
@justinmc @dionjwa fixed via #118 and tested in deployment.
