### ISSUE TITLE
404

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-design-applications#55]
The 404 page is ugly!

![screen shot 2017-01-06 at 3 45 21 pm](https://cloud.githubusercontent.com/assets/389558/21736666/2da6bce0-d427-11e6-8883-00d0c2980d96.png)

**Comment by PeterRJones** [comment]
Do you need an app-specific page or can you use this default: http://notreal.bionano.autodesk.com/
@MalteTinnus thoughts ?

**Comment by PeterRJones** [comment]
@justinmc This page, if used, is shown automatically when the app returns a 404

**Comment by justinmc** [comment]
@PeterRJones Ah I think I need to map the frontend routes to the backend routes so that this works correctly.  Right now the server redirects most "not found" routes to the main app anyway so that the frontend can handle routing.

@MalteTinnus We'll still need to handle the situation where the user loads a nonexistent workflow on the frontend though (like `/workflow/fakeworkflowid` will not show Peter's 404 page, it will load the app).

**Comment by justinmc** [comment]
Fixed with https://github.com/Autodesk/molecular-design-applications/pull/179
