### ISSUE TITLE
Test Route

### ISSUE THREAD

**Issue by justinmc** [Autodesk/molecular-design-applications#73]
Create a route that can be used as an end to end test for the entire app.  Should run the VDE workflow.  Needed by @PeterRJones.

- [x] Get basic route and return interface in place
- [x] Hook up to build 
- [x] Hook up to monitoring
~- [ ] Extented Test route to exercise complete workflow run (/test-all)~ (moved to issue #103 )

**Comment by PeterRJones** [comment]
This would be a rest endpoint `/test` which returns json payload and http 200 upon success. upon failures return is http non-200 (usually 400/500) and if possible failure payload. 

Success will be determined by (i) http return of 200 and (ii) json payload value showing success (e.g. { "success": true } or something)

**Comment by justinmc** [comment]
@PeterRJones Let me know if this works: https://github.com/Autodesk/molecular-design-applications/pull/83

Note that this will not test an entire workflow execution, it will just test that a workflow can be successfully submitted.  Maybe we can rethink this if we need to test more robustly, but right now, the fastest workflow takes ~10 minutes to run so it's not practical to use for this route.

**Comment by PeterRJones** [comment]
@justinmc See note on PR. Desired end state is that this route test as much of a complete wf run as possible. However if that is ~10 min each time, then I agree, we should reduce the scope of this route to do something simpler. When this tied to a health monitor, the max duration of that monitor is 3 minutes - what can we test of this within 3 minutes ?
