### ISSUE TITLE
Frontend UX punchlist

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-applications#76]
From @MalteTinnus - this collects issues not captured elsewhere

Prioritized list for Justin (duplicates items from below):
1. [x] Emails: Fix link (currently links to http://undefined) in emails
2. [x] UI text fields: Put ‘Enter’ button behind all inputs
5. [x] Results: Ability to dynamically specify results text fields and units
3. [x] Workflow steps: Replace green dot with green checkmark
3. [x] Workflow steps: Steps not clickable (and have 0.5 alpha) until previous step has checkmark
4. [x] Workflow steps: When step is ready (ie previous step has green checkmark), the label throbs (fades in /out from 0.5 to 1 opacity once previous one has finished); after click, stops throbbing and becomes 100% opaque
5. [x] Workflow steps: no rollover indication unless they are clickable
6. [x] Rename ‘Run’ to ’Run Workflow’
7. [ ] Text fields for email and PDB ID and SMILES, etc, should keep values even when clicking back and forth between different workflow steps

Homepage
- [x] Setup nav
- [x] Hook up (or hide) twitter and facebook sharing buttons
- [x] Dynamic ‘runs’ and ‘views’ numbers for each app
- [x] Cleanup
- [ ] Creator headshots

Apps
- [x] Hookup (or hide) sharing buttons
- [x] Numbering of steps
- [x] Clarify input types for VERTICAL DETACHMENT ENERGY:
  * Text area + select one of: SMILES, IUPAC name, inCHI key
  * Or upload: XYZ, SDF, mol2, mmcif, PDB
- [x] Clarify input file type for LIGAND REFINEMENT:
  * Enter PDB ID (text area), or upload PDB/mmCIF - no radio buttons
- [x] Cleanup

Results pages
- [x] Fix link (currently links to http://undefined) in emails
- [x] Different output field names for minimization and VDE

**Comment by justinmc** [comment]
After catching up with @MalteTinnus this morning, here are a few updates:

  - [ ] Homepage social buttons should just be hidden
  - [ ] Add PDBID title in view after upload
  - [ ] Cancel workflow confirmation
  - [ ] Canceled page design
  - [ ] Canceled status should redirect to the workflow
  - [ ] Links on "thank you" page

**Comment by justinmc** [comment]
Dynamic runs and views in this PR: https://github.com/Autodesk/molecular-design-applications/pull/92

**Comment by justinmc** [comment]
Also homepage nav anchors in https://github.com/Autodesk/molecular-design-applications/pull/92 as a bonus!

**Comment by justinmc** [comment]
Another update from Malte in Slack:

Workflows
 - [ ] Put ‘Enter’ button behind all inputs
 - [ ] PDB and Email
 - [ ] Replace green dot with green checkmark
 - [ ] Next step only selectable if previous one has checkmark
 - [ ] No rollover indication
 - [ ] Steps with checkmarks are freely selectable
 - [ ] Text fields should keep entered text
 - [ ] Next step label fades in /out from 0.5 to 1 opacity once previous one has finished
 - [ ] Stops animation once clicked
 - [ ] Stays at 1 opacity
 - [ ] Add loading bar at bottom when loading PBD
 - [ ] Replace current ‘Run’ button with step button and number it. Put directly underneath all other steps
 - [ ] Rename ‘Run’ to ’Run Workflow’
 - [ ] Move ‘About’ to where ‘Run’ was
 - [ ] Rewrite text in ’Enter email’ step to: ‘Enter email. Once you click ‘Run Workflow’ we will send an email…’ (Aaron)

Running web page
 - [ ] Results page should replace waiting page automatically
 - [ ] Animation on running page missing

Result step
 - [ ] ‘Download button’ doesn’t work
 - [ ] Remove ‘Share’
 - [ ] Remove ‘Colorize’

Email
 - [ ] Remove blue and black box from email (Aaron)
 - [ ] Image don’t load
 - [ ] Clicking ‘view results’ should open workflow with ‘Results’ step selected

VDE
 - [ ] Add text in ‘Load molecule’ step (Aaron)
 - [ ] Input: Enter molecule here
 - [ ] Text underneath: Accepts SMILES, IUPAC, INCHI
—
 - [ ] Text: Or upload file.
 - [ ] Text: Accepts XYZ, SDF, MOL2, PDB, mmCIF
 - [ ] Button: Browse File

**Comment by justinmc** [comment]
Some results checkboxes ticked with: https://github.com/Autodesk/molecular-design-applications/pull/130

**Comment by justinmc** [comment]
@avirshup I'm going to close this issue in favor of specific smaller issues for anything that's still left.

Issues mentioned here:
https://github.com/Autodesk/molecular-design-applications/issues/176
https://github.com/Autodesk/molecular-design-applications/issues/177

PRs in progress mentioned here:
https://github.com/Autodesk/molecular-design-applications/pull/158
https://github.com/Autodesk/molecular-design-applications/pull/175

Let me know if there's anything else I'm missing here.  It's probably worth going over this with Malte when he gets back, because I wasn't sure on some of the last unchecked points here.
